# 开启Travis CI任务, 提交后自动生成测试报告。
sudo: false
language: cpp
os:
  - linux

compiler:
  - gcc
script:
  - sudo apt-get update -y
  - sudo apt-get install libboost-all-dev -y
  - sudo apt-get install aptitude -y
  - aptitude search boost -y
  - sudo apt-get install scons -y
  - scons

after_success: 
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

